<?php
/**
 * MUFlash.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFlash
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jan 27 19:27:23 CET 2012.
 */

/**
 * Generic item list content plugin implementation class
 */
class MUFlash_ContentType_ItemList extends MUFlash_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function MUFlash_Api_ContentTypes_itemlist($args)
{
    return new MUFlash_Api_ContentTypes_itemListPlugin();
}
