<?php
/**
 * MUFlash.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFlash
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jan 27 19:27:23 CET 2012.
 */


/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for movie entities.
 */
class MUFlash_Entity_Validator_Base_Movie extends MUFlash_Validator
{


    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('MUFlash');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('description', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('description', 2000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('preview', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('preview', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('flashFile', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('flashFile', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('backgroundColour', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('backgroundColour', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('backgroundColour')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('backgroundColour'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('play')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('play'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('playLoop')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('playLoop'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('width', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('width', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('width')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('width'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('height', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('height', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('height')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('height'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('playerVersion', 50)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('playerVersion', 50), $dom);
            return $errorInfo;
        }
        if (!$this->isUniqueValue('title')) {
            $errorInfo['message'] = __f('The title %s is already assigned. Please choose another title.', array($this->entity['title']), $dom);
            return $errorInfo;
        }
        if (!$this->isUniqueValue('flashFile')) {
            $errorInfo['message'] = __f('The flash file %s is already assigned. Please choose another flash file.', array($this->entity['flashFile']), $dom);
            return $errorInfo;
        }
        return true;
    }


    /**
     * Check for unique values.
     *
     * This method determines if there already exist movies with the same movie.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given movie does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if (empty($this->entity[$fieldName])) {
            return false;
        }

        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('MUFlash_Entity_Movie');

        $excludeid = $this->entity['id'];
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }

    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }


}
