<?php
/**
 * MUFlash.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFlash
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jan 27 19:27:23 CET 2012.
 */

/**
 * Installer base class
 */
class MUFlash_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the MUFlash application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        $basePath = MUFlash_Util_Controller::getFileBaseFolder('movie', 'preview');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }
        $basePath = MUFlash_Util_Controller::getFileBaseFolder('movie', 'flashFile');
        if (!is_dir($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" does not exist. Please create it before installing this application.', array($basePath)));
        }
        if (!is_writable($basePath)) {
            return LogUtil::registerError($this->__f('The upload folder "%s" is not writable. Please change permissions accordingly before installing this application.', array($basePath)));
        }

        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while creating the tables for the %s module.', array($this->getName())));
        }

        // create the default data for MUFlash
        $this->createDefaultData();

        // register persistent event handlers
        $this->registerPersistentEventHandlers();

        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());


        // initialisation successful
        return true;
    }

    /**
     * Upgrade the MUFlash application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldversion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldversion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldversion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
                }
        }
    */

        // update successful
        return true;
    }

    /**
     * Uninstall MUFlash.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s module.', array($this->getName())));
        }

        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
        }

        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers('MUFlash');

        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());


        // deletion successful
        return true;
    }

    /**
     * Build array with all entity classes for MUFlash.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'MUFlash_Entity_Movie';

        return $classNames;
    }
    /**
     * Create the default data for MUFlash.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        // Ensure that tables are cleared
        $this->entityManager->transactional(function($entityManager) {
            $entityManager->getRepository('MUFlash_Entity_Movie')->truncateTable();
        });

        // Insertion successful
        return true;
    }

    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core
        EventUtil::registerPersistentModuleHandler('MUFlash', 'api.method_not_found', array('MUFlash_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'core.preinit', array('MUFlash_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'core.init', array('MUFlash_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'core.postinit', array('MUFlash_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'controller.method_not_found', array('MUFlash_Listener_Core', 'controllerMethodNotFound'));

        // installer
        EventUtil::registerPersistentModuleHandler('MUFlash', 'installer.module.installed', array('MUFlash_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'installer.module.upgraded', array('MUFlash_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'installer.module.uninstalled', array('MUFlash_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'installer.subscriberarea.uninstalled', array('MUFlash_Listener_Installer', 'subscriberAreaUninstalled'));

        // modules
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module_dispatch.postloadgeneric', array('MUFlash_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module_dispatch.preexecute', array('MUFlash_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module_dispatch.postexecute', array('MUFlash_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module_dispatch.custom_classname', array('MUFlash_Listener_ModuleDispatch', 'customClassname'));

        // mailer
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.mailer.api.sendmessage', array('MUFlash_Listener_Mailer', 'sendMessage'));

        // page
        EventUtil::registerPersistentModuleHandler('MUFlash', 'pageutil.addvar_filter', array('MUFlash_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'system.outputfilter', array('MUFlash_Listener_Page', 'systemOutputfilter'));

        // errors
        EventUtil::registerPersistentModuleHandler('MUFlash', 'setup.errorreporting', array('MUFlash_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'systemerror', array('MUFlash_Listener_Errors', 'systemError'));

        // theme
        EventUtil::registerPersistentModuleHandler('MUFlash', 'theme.preinit', array('MUFlash_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'theme.init', array('MUFlash_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'theme.load_config', array('MUFlash_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'theme.prefetch', array('MUFlash_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'theme.postfetch', array('MUFlash_Listener_Theme', 'postFetch'));

        // view
        EventUtil::registerPersistentModuleHandler('MUFlash', 'view.init', array('MUFlash_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'view.postfetch', array('MUFlash_Listener_View', 'postFetch'));

        // user login
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.login.started', array('MUFlash_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.login.veto', array('MUFlash_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.login.succeeded', array('MUFlash_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.login.failed', array('MUFlash_Listener_UserLogin', 'failed'));

        // user logout
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.logout.succeeded', array('MUFlash_Listener_UserLogout', 'succeeded'));

        // user
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.gettheme', array('MUFlash_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.account.create', array('MUFlash_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.account.update', array('MUFlash_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.account.delete', array('MUFlash_Listener_User', 'delete'));

        // registration
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.registration.started', array('MUFlash_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.registration.succeeded', array('MUFlash_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.ui.registration.failed', array('MUFlash_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.registration.create', array('MUFlash_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.registration.update', array('MUFlash_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'user.registration.delete', array('MUFlash_Listener_UserRegistration', 'delete'));

        // users module
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.users.config.updated', array('MUFlash_Listener_Users', 'configUpdated'));

        // group
        EventUtil::registerPersistentModuleHandler('MUFlash', 'group.create', array('MUFlash_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'group.update', array('MUFlash_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'group.delete', array('MUFlash_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'group.adduser', array('MUFlash_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'group.removeuser', array('MUFlash_Listener_Group', 'removeUser'));

        // special purposes and 3rd party api support
        EventUtil::registerPersistentModuleHandler('MUFlash', 'get.pending_content', array('MUFlash_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('MUFlash', 'module.content.gettypes', array('MUFlash_Listener_ThirdParty', 'contentGetTypes'));
    }
}
