<?php
/**
 * MUFlash.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFlash
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jan 27 19:27:23 CET 2012.
 */

/**
 * Version information base class.
 */
class MUFlash_Base_Version extends Zikula_AbstractVersion
{
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('MUFlash');
        // the module description
        $meta['description']          = $this->__('MUFlash module generated by ModuleStudio 0.5.4.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('muflash');
        // core requirement
        $meta['core_min']             = '1.3.1'; // requires minimum 1.3.1 or later
        $meta['core_max']             = '1.3.99'; // not ready for 1.4.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        // DEBUG: permission schema aspect starts
        $meta['securityschema'] = array(
            'MUFlash::' => '::',

            'MUFlash:Movie:' => 'MovieID::'
        );
        // DEBUG: permission schema aspect ends



        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muflash.ui_hooks.movies', 'ui_hooks', __('muflash Movies Display Hooks'));
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'muflash.ui_hooks.movies.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'muflash.ui_hooks.movies.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'muflash.ui_hooks.movies.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'muflash.ui_hooks.movies.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'muflash.ui_hooks.movies.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'muflash.ui_hooks.movies.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'muflash.ui_hooks.movies.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muflash.filter_hooks.movies', 'filter_hooks', __('muflash Movies Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'muflash.filter_hooks.movies.filter');
        $this->registerHookSubscriberBundle($bundle);


    }
}

