<?php
/**
 * MUFlash.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUFlash
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Jan 27 19:27:23 CET 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUFlash_admin_edit() function.
 * It aims on the movie object type.
 */
class MUFlash_Form_Handler_Admin_Movie_Edit extends MUFlash_Form_Handler_Admin_Movie_Base_Edit
{
    // feel free to extend the base handler class here
}
